#!/usr/bin/env bash
# This script audits for domain and subdomains 
#Usage: $0 <domain> <subdomain>

# Function to display information about a subdomain
display_subdomain_info() {
    local domain="$1"
    local subdomain="$2"
    local dig_output
    dig_output=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION/{flag=1;next}/;;/{flag=0}flag' | awk '{print $1,$2,$3,$4,$5}')
    local record_type
    record_type=$(echo "$dig_output" | awk '{print $4}')
    local destination
    destination=$(echo "$dig_output" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}


# Default subdomains to audit
default_subdomains=("www" "lb-01" "web-01" "web-02")

# Check if both domain and subdomain were provided as arguments
if [ $# -eq 2 ]; then
    display_subdomain_info "$1" "$2"
# Otherwise, display information about default subdomains for the given domain
elif [ $# -eq 1 ]; then
    for subdomain in "${default_subdomains[@]}"; do
        display_subdomain_info "$1" "$subdomain"
    done
fi
