#!/usr/bin/env bash
# Script that transfers file from client to a server

# Set parameters
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Check if at least 4 parameters are passed
if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
else
	scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username"@"$ip":/home/"$username"
fi

