#!/usr/bin/env bash
# Script that configures Nginx to listen to port 80 for all IPV4

# Backup Nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Stop Nginx service
sudo service nginx stop

# Update Nginx configuration file
sudo sed -i 's/listen 8080;/listen 0.0.0.0:80;/g' /etc/nginx/sites-available/default

# Restart Nginx service
sudo service nginx start

echo "Nginx configuration has been updated to use port 80 for all IPv4 IPs."

