#!/usr/bin/env bash
# This script removes the default Nginx configuration from sites-enabled,
# creates a symbolic link to the default configuration in sites-enabled,
# and restarts the Nginx service.

# Remove default configuration from sites-enabled
sudo rm /etc/nginx/sites-enabled/default

# Create symbolic link to default configuration in sites-enabled
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart Nginx service
sudo service nginx restart

