#!/usr/bin/env bash
#script that displays 'Best School' 10 times, but for the 9th iteration, displays 'Best School' and then 'Hi' on a new line.
START=1
END=10
i=$START
while [[ $i -le END ]]
do
    echo "Best School"
if [[ $i -eq 9 ]]
then
    echo "Hi"
fi
i=$((i+1))
done
