#!/usr/bin/env bash
#Bash script that loops from     displays Best School for the other iterations
START=1
END=10

i=$START

while [ $i -le $END ]
do
    if [ $i -eq 4 ]
    then
        echo "bad luck"
    elif [ $i -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
