#!/usr/bin/bash
# Installs and configures ufw to block all incoming traffic
# except for port 22, 443, 80. all outgoing traffic is allowed

sudo apt-get install ufw -y
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable -y
sudo ufw status
