#!/usr/bin/env bash
# A script that creates  an RSA key pair

# Set the name of the private key file
key_name="school"

# Generate the key pair with 4096 bits and passphrase protection
ssh-keygen -t rsa -b 4096 -f ~/.ssh/"$key_name" -N "betty"

